version: '3.7'

services:
  regression:
    image: ${ARCTERN_REPO}:${ARCTERN_TAG}
    volumes:
      - ../..:/arctern
    command: &spark-test
      ["/arctern/ci/scripts/run_spark_regression.sh", "--master", "spark://spark-master:7077", "--conda_env=arctern", "/arctern/tests/spark_test.py"]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 200M
networks:
  default:
    external:
      name: ${ARCTERN_NETWORK}