version: '3.7'

services:
  regression:
    # Usage:
    #   docker-compose run --rm regression
    image: ${ARCTERN_SPARK_TARGET_REPO}:${ARCTERN_SPARK_TARGET_TAG}
    volumes:
      - ../..:/arctern
    command: &spark-test
      ["/arctern/ci/scripts/run_spark_regression.sh", "--master", "spark://spark-master:7077", "/arctern/tests/spark_test.py", "/arctern/tests/draw_map_test.py", "/arctern/tests/draw_plot_test.py"]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 200M
  restful-regression:
    # Usage:
    #   docker-compose build restful-regression
    #   docker-compose run --rm restful-regression
    image: ${RESTFUL_PYTEST_REPO}:${RESTFUL_PYTEST_TAG}
    build:
      context: ../..
      dockerfile: docker/test_env/restful-pytest.dockerfile
      cache_from:
        - ${RESTFUL_PYTEST_REPO}:${RESTFUL_PYTEST_TAG}
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ../../gui/server/arctern_server:/arctern/gui/server/arctern_server
    working_dir: /arctern/gui/server/arctern_server/tests/restful
    command: &flask-test
      ["pytest", "--host", "flask", "--port", "8080", "--config", "/arctern/gui/server/arctern_server/db.json", "-p", "no:cacheprovider", "-s"]
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 200M
