version: '3.7'

services:
  regression:
    image: ${ARCTERN_REPO}:${ARCTERN_TAG}
    volumes:
      - ../..:/arctern
    command: &spark-test
      ["/arctern/ci/scripts/run_spark_regression.sh", "--master", "spark://spark-master:7077", "/arctern/tests/spark_test.py", "/arctern/tests/draw_map_test.py", "/arctern/tests/draw_plot_test.py"]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 200M
  restful-regression:
    image: ${PYTEST_REPO}:${PYTEST_TAG}
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ../../gui/server:/arctern/gui/server
    working_dir: /arctern/gui/server/tests/restful
    command: &flask-test
      ["pytest", "--host", "flask", "--port", "8080", "--config", "/arctern/gui/server/db.json", "-p", "no:cacheprovider"]
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 200M
